language: python
python:
- "3.4"
- "3.5"
- "3.6"
env:
- DJANGO_VERSION=<1.9
- DJANGO_VERSION=<1.10
- DJANGO_VERSION=<1.11
install:
- pip install -r requirements/test.txt
- pip install -q Django$DJANGO_VERSION
script:
- python -m pytest test --cov=ridi
after_success:
- coveralls
deploy:
  provider: pypi
  user: ridi-data
  password:
    secure: "gN4U7TRYb8IXMaoytq1DoMTtl+WBTCkItuuRUgcsTWG437nZ2zcTPpyeiPdM6Y87xsUDYMs0xxvPpnPfgdsSR4Z8A7S7SXwhXzff8ELDVr4GiDXMRaz0UgzlC29Sh7aqaMCr5JZ70bwGC/GkiUZal3cjCUUVyT3WVhawqpZX2aNmN388VuPoQ5T7hH0gYy/yP+2oZzcJunnWwJc/IassxwNQCxe/KxYDQ+Yuqrg8bL+kZs2gmAe/J7/0K5gxTBvdL0LRDJ6rYbAExWkN7a9O9URXLD/gfD2lFTkZkZHoRB47FlsETWboDGic3cdG2jssgO+VuSH+K8OO/ruu+uobCPL4AmLSAMxF18bVxtKxMlfhLoihWa3pEzAtrjyc9sHBOexwIWdbB5VY3hkgpEOTAavBdXdUwxKVHcGyZ/NnT6/dzaoAm6PwV6mD3GYiHfzC5nsbh8OMmhU1qYc1GfVzYJ7HDRC/7fxYx9RvhhXVpoiFdEdqSOmF8oHGP69RXJr64NsvtEa3d0ggkHTBH15quV3vCNIPQqEbb3S+wCpgawel/oNuQYlbsawD3sgsRXAo7AQ3wx+PNXXSPfSOPM91xKYphdMu3y0xoae0ID8cYR4CWjM5jTvzcqvf9remJRkN3Jm3UYkyw2rx079xgOCMGStx14pD7vA0eMmJddYy5+o="
  on:
    branch: master
    python: "3.6"
